"""empty message

Revision ID: 05698a16520a
Revises: cf8cc38aa041
Create Date: 2022-01-28 22:05:57.885406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05698a16520a'
down_revision = 'cf8cc38aa041'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'price',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
