"""empty message

Revision ID: 9c086ca1e5de
Revises: 05698a16520a
Create Date: 2022-01-31 18:48:58.540051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c086ca1e5de'
down_revision = '05698a16520a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
